#!/usr/bin/env python3
"""make_table1_latex.py

Convert vSAVE-1.1 Table 1 CSV into a NeurIPS-ready LaTeX table.

Input:  exp/summary/table1.csv (generated by make_table1.py)
Output: exp/summary/table1.tex

This script ONLY formats the already-computed Table 1.
It does NOT recompute bootstrap CIs.

Usage:
  python make_table1_latex.py \
    --table1_csv exp/summary/table1.csv \
    --out_tex exp/summary/table1.tex \
    --caption "Controlled vs Baseline results" \
    --label "tab:table1"

Tip:
- If you want a compact table for NeurIPS main text, use --compact.
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path
from typing import Dict, List, Tuple


DEFAULT_COLUMNS_FULL = [
    ("pillar", "Pillar"),
    ("n_seeds", "N"),
    ("collapse_rate_baseline", "Collapse (Base)"),
    ("collapse_rate_controlled", "Collapse (Ctrl)"),
    ("delta_collapse", "ΔCollapse"),
    ("delta_collapse_95ci", "95% CI"),
    ("RR_collapse", "RR"),
    ("RR_collapse_95ci", "RR 95% CI"),
    ("OR_collapse", "OR"),
    ("OR_collapse_95ci", "OR 95% CI"),
    ("intervene_rate_primary", "Intervene-any"),
    ("intervene_density_secondary", "Intervene dens."),
    ("delta_runtime_sec", "ΔRuntime (s)"),
]

DEFAULT_COLUMNS_COMPACT = [
    ("pillar", "Pillar"),
    ("n_seeds", "N"),
    ("collapse_rate_baseline", "Collapse (Base)"),
    ("collapse_rate_controlled", "Collapse (Ctrl)"),
    ("delta_collapse", "ΔCollapse"),
    ("delta_collapse_95ci", "95% CI"),
    ("RR_collapse", "RR"),
    ("OR_collapse", "OR"),
    ("intervene_rate_primary", "Intervene-any"),
]


def _fmt_float(x: str, nd: int) -> str:
    try:
        v = float(x)
    except Exception:
        return x
    # Keep 0 exactly as 0.0? NeurIPS tables look cleaner with fixed decimals.
    return f"{v:.{nd}f}"


def _fmt_int(x: str) -> str:
    try:
        return str(int(float(x)))
    except Exception:
        return x


def _latex_escape(s: str) -> str:
    # Minimal escaping for table text.
    return (
        s.replace("\\", "\\textbackslash{}")
        .replace("&", "\\&")
        .replace("%", "\\%")
        .replace("$", "\\$")
        .replace("#", "\\#")
        .replace("_", "\\_")
        .replace("{", "\\{")
        .replace("}", "\\}")
        .replace("~", "\\textasciitilde{}")
        .replace("^", "\\textasciicircum{}")
    )


def read_table1_csv(path: Path) -> List[Dict[str, str]]:
    rows: List[Dict[str, str]] = []
    with path.open("r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for r in reader:
            rows.append({k: (v if v is not None else "") for k, v in r.items()})
    if not rows:
        raise RuntimeError(f"table1.csv is empty: {path}")
    return rows


def add_ci_columns(rows: List[Dict[str, str]]) -> None:
    # make_table1.py outputs low/high columns; we merge them into a single CI string.
    for r in rows:
        if "delta_collapse_ci_low" in r and "delta_collapse_ci_high" in r:
            lo = r.get("delta_collapse_ci_low", "")
            hi = r.get("delta_collapse_ci_high", "")
            r["delta_collapse_95ci"] = f"[{lo}, {hi}]"
        if "RR_collapse_ci_low" in r and "RR_collapse_ci_high" in r:
            lo = r.get("RR_collapse_ci_low", "")
            hi = r.get("RR_collapse_ci_high", "")
            r["RR_collapse_95ci"] = f"[{lo}, {hi}]"
        if "OR_collapse_ci_low" in r and "OR_collapse_ci_high" in r:
            lo = r.get("OR_collapse_ci_low", "")
            hi = r.get("OR_collapse_ci_high", "")
            r["OR_collapse_95ci"] = f"[{lo}, {hi}]"


def format_cell(col: str, val: str, nd: int) -> str:
    if col in {"pillar"}:
        return _latex_escape(val)
    if col in {"n_seeds"}:
        return _fmt_int(val)

    # rates and deltas
    if col.startswith("collapse_rate") or col in {"delta_collapse", "intervene_density_secondary"}:
        return _fmt_float(val, nd)

    if col in {"RR_collapse", "OR_collapse", "delta_runtime_sec"}:
        return _fmt_float(val, nd)

    if col in {"intervene_rate_primary"}:
        # It's a rate; keep decimals to match others.
        return _fmt_float(val, nd)

    if col.endswith("95ci"):
        # CI is a string like [a, b]
        # Format numbers inside if possible.
        s = val.strip()
        if s.startswith("[") and s.endswith("]"):
            inner = s[1:-1]
            parts = [p.strip() for p in inner.split(",")]
            if len(parts) == 2:
                lo = _fmt_float(parts[0], nd)
                hi = _fmt_float(parts[1], nd)
                return _latex_escape(f"[{lo}, {hi}]")
        return _latex_escape(val)

    # fallback
    return _latex_escape(val)


def build_tabular(
    rows: List[Dict[str, str]],
    columns: List[Tuple[str, str]],
    nd: int,
) -> str:
    # Align: first column left, rest right.
    align = "l" + "r" * (len(columns) - 1)

    header = " & ".join(_latex_escape(h) for _, h in columns) + " \\\\"

    body_lines: List[str] = []
    for r in rows:
        cells = [format_cell(col, r.get(col, ""), nd) for col, _ in columns]
        body_lines.append(" & ".join(cells) + " \\\\"
                         )

    tab = []
    tab.append(f"\\begin{{tabular}}{{{align}}}")
    tab.append("\\toprule")
    tab.append(header)
    tab.append("\\midrule")
    tab.extend(body_lines)
    tab.append("\\bottomrule")
    tab.append("\\end{tabular}")
    return "\n".join(tab)


def wrap_table(
    tabular: str,
    caption: str,
    label: str,
    position: str,
    fontsize: str,
    use_resizebox: bool,
) -> str:
    lines: List[str] = []
    lines.append(f"\\begin{{table}}[{position}]")
    if fontsize:
        lines.append(f"\\{fontsize}")
    lines.append("\\centering")

    if use_resizebox:
        lines.append("\\resizebox{\\linewidth}{!}{%")
        lines.append(tabular)
        lines.append("}")
    else:
        lines.append(tabular)

    if caption:
        lines.append(f"\\caption{{{_latex_escape(caption)}}}")
    if label:
        lines.append(f"\\label{{{_latex_escape(label)}}}")
    lines.append("\\end{table}")
    return "\n".join(lines) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--table1_csv", type=str, required=True)
    ap.add_argument("--out_tex", type=str, required=True)
    ap.add_argument("--caption", type=str, default="")
    ap.add_argument("--label", type=str, default="tab:table1")
    ap.add_argument("--position", type=str, default="t")
    ap.add_argument("--decimals", type=int, default=3, help="decimal places for floats")
    ap.add_argument("--compact", action="store_true", help="make a more compact main-text table")
    ap.add_argument(
        "--fontsize",
        type=str,
        default="small",
        choices=["", "scriptsize", "footnotesize", "small", "normalsize"],
        help="LaTeX fontsize command name (without backslash)",
    )
    ap.add_argument(
        "--resizebox",
        action="store_true",
        help="wrap tabular with resizebox(\\linewidth) for tight columns",
    )

    args = ap.parse_args()

    csv_path = Path(args.table1_csv)
    out_path = Path(args.out_tex)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    rows = read_table1_csv(csv_path)
    add_ci_columns(rows)

    cols = DEFAULT_COLUMNS_COMPACT if args.compact else DEFAULT_COLUMNS_FULL
    tabular = build_tabular(rows, cols, nd=int(args.decimals))
    tex = wrap_table(
        tabular,
        caption=args.caption,
        label=args.label,
        position=args.position,
        fontsize=args.fontsize,
        use_resizebox=bool(args.resizebox),
    )

    out_path.write_text(tex, encoding="utf-8")
    print(f"[make_table1_latex] wrote: {out_path}")


if __name__ == "__main__":
    main()
